basePath: /api
definitions:
  types.ChatCompletionResponse:
    properties:
      choices:
        items:
          $ref: '#/definitions/types.Choice'
        type: array
      created:
        type: integer
      id:
        type: string
      model:
        type: string
      object:
        type: string
      usage:
        $ref: '#/definitions/types.Usage'
    type: object
  types.ChatMessage:
    properties:
      content:
        type: string
      role:
        enum:
        - system
        - user
        - assistant
        type: string
    required:
    - content
    - role
    type: object
  types.Choice:
    properties:
      finish_reason:
        type: string
      index:
        type: integer
      message:
        $ref: '#/definitions/types.ChatMessage'
    type: object
  types.ConsumeModelRequest:
    properties:
      max_cost:
        type: number
      messages:
        items:
          $ref: '#/definitions/types.ChatMessage'
        minItems: 1
        type: array
      model_key:
        type: string
      options:
        additionalProperties: true
        type: object
    required:
    - max_cost
    - messages
    - model_key
    type: object
  types.Usage:
    properties:
      completion_tokens:
        type: integer
      prompt_tokens:
        type: integer
      total_tokens:
        type: integer
    type: object
info:
  contact:
    email: your@mail.com
    name: API Support
  description: This is an auto-generated API Docs.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: API
  version: "1.0"
paths:
  /v1/ai/consume:
    post:
      consumes:
      - application/json
      description: Send a consume model request to the AI provider.
      parameters:
      - description: Consume model request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/types.ConsumeModelRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.ChatCompletionResponse'
      security:
      - ApiKeyAuth: []
      summary: consume an AI model
      tags:
      - AI
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
